default_agent: multiagent_agentcore_runtime
agents:
  multiagent_agentcore_runtime:
    name: multiagent_agentcore_runtime
    entrypoint: /home/bk/_src/github.com/balakrishnangithub/aws-agentcore-examples/multiagent-agentcore-runtime.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: /home/bk/_src/github.com/balakrishnangithub/aws-agentcore-examples
    aws:
      execution_role: null
      execution_role_auto_create: true
      account: '913043759616'
      region: us-west-2
      ecr_repository: null
      ecr_auto_create: true
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: multiagent_agentcore_runtime_mem-ur2N614wRM
      memory_arn: arn:aws:bedrock-agentcore:us-west-2:913043759616:memory/multiagent_agentcore_runtime_mem-ur2N614wRM
      memory_name: multiagent_agentcore_runtime_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
